import pylab
from collections import OrderedDict
import argparse
import numpy as np

def main():
    parser = argparse.ArgumentParser(description='Plots CSV files generated by analyze.py')
    parser.add_argument('csvfile', type=str,
                        help='CSV file to plot')


    parser.add_argument('--output', type=str,
                        default='',
                        help='Output file of the graph')

    args = parser.parse_args()

    with open(args.csvfile) as f:
        lines = f.read().split('\n')
        ydata_01 = [float(w.strip())*100 for w in lines[1: 101]]
        ydata_05 = [float(w.strip())*100 for w in lines[102: 202]]
        ydata_10 = [float(w.strip())*100 for w in lines[203: -1]]

    pylab.plot(range(0, 1000000, 10000), ydata_01)
    pylab.xlabel('Query number')
    pylab.ylabel('% speedup')
    pylab.title('Speedup vs number of queries made')
    pylab.grid(True)
    pylab.show()
    pylab.plot(range(0, 1000000, 10000), ydata_05)
    pylab.xlabel('Query number')
    pylab.ylabel('% speedup')
    pylab.title('Speedup vs number of queries made')
    pylab.grid(True)
    pylab.show()
    pylab.plot(range(0, 1000000, 10000), ydata_10)
    pylab.xlabel('Query number')
    pylab.ylabel('% speedup')
    pylab.title('Speedup vs number of queries made')
    pylab.grid(True)
    pylab.show()

if __name__ == '__main__':
    main()
